### ISSUE TITLE
JP ship ID 20000 cause the port mapping conflict in parse_packet.

### ISSUE THREAD

**Issue by KagefumiMerry** [AntonnMal/pso2-proxy#2]
Since I have no idea about the usage about ship ID 20000 in ship list packet, may be simply skip it should be ok.
but not sure why before code refactoring, manually changing the IP and ports in source code will be fine for JP, even the port maybe conflict.

![image](https://github.com/AntonnMal/pso2-proxy/assets/9698241/5305685d-8633-4522-926a-b052897e52fa)

As current, I have to use the dumb coding for making the proxy work for JP:

```rust
else if let Packet::ShipList(ships) = packet {
        for ship in &mut ships.ships {
			println!("[parse_packet] ship name {0}, id {1}, with ip {2}", ship.name, ship.id,ship.ip);
            let ip = ship.ip;
			let jp_shipnum = ship.id / 1000;
			if jp_shipnum == 10 {
				let jp_port = 12000 as u16;
				push_listener(sockets, SocketAddr::from((ip, jp_port)));
			} else if jp_shipnum == 20 {
				let jp_port = 13000 as u16;
				push_listener(sockets, SocketAddr::from((ip, jp_port)));
			} else {
				let jp_port = (12000 + jp_shipnum * 100 ) as u16;
				push_listener(sockets, SocketAddr::from((ip, jp_port)));
			}
			//println!("openting port {}",jp_port);
            ship.ip = callback_ip;
        }
    }
```

**Comment by AntonnMal** [comment]
Should be "fixed" as of cfeaa6833e76b2db09f69761b03a6d8f48fd055e. Not closing this issue myself, because this might not be the desired fix.
