### ISSUE TITLE
How to obtain SEGAKey.blob?

### ISSUE THREAD

**Issue by crispbitload** [AntonnMal/pso2-proxy#4]
Compiled the proxy, but I can't seem to find a way/find a source to grab SEGAKey.blob.

Went to cyberkitsunes github as well for methods to grab the key, but it just states to ask in a IRC channel (which seems to be pretty dead at the moment)

(also looking for both keys for JP and US, if they are different)

**Comment by AntonnMal** [comment]
The [RSA injector](https://github.com/AntonnMal/pso2-rsa-injector) can dump public keys. You'll need to enable `grab_keys` option.

**Comment by crispbitload** [comment]
Got it, thanks!

![Screenshot 2024-07-08 224623](https://github.com/AntonnMal/pso2-proxy/assets/84352107/6ff31690-2a83-41eb-94bc-0b0cb443de4c)

**Comment by crispbitload** [comment]
I was wondering, how do I get this fully running? I tried running it and launching the JP version, and I have not gotten any packets at all.

I obtained the server link via http://the-ghf-clan.de/pso2serverstatus.html

**Comment by AntonnMal** [comment]
Did you add the IP replacement in the injector's config file?

**Comment by crispbitload** [comment]
I have added the IP replacement to the config (To account for the JP server)

![Screenshot 2024-07-09 105243](https://github.com/AntonnMal/pso2-proxy/assets/84352107/1b6f774e-4913-43ba-bf36-366f15c6aa3a)

Still no luck grabbing packets

**Comment by AntonnMal** [comment]
That's not the config I'm talking about. I meant the config that you've set up during the key grabbing process.

**Comment by crispbitload** [comment]
I disabled the replace address option, ill add the links and re-enable it (If I need to replace them)

![Screenshot 2024-07-09 190648](https://github.com/AntonnMal/pso2-proxy/assets/84352107/b1c2eea3-13ef-4e83-a61b-707ed8ad7735)

My apologies, also do I add the same link I added in the config for JP? or use different links?

**Comment by AntonnMal** [comment]
Yes, you'll need to replace (and possibly add more fields) the IPs with the JP ones.

**Comment by crispbitload** [comment]
Got it, is there a file I can grab/place I can look to obtain the other links? Similar to unpacking the FPK file back on the vita version, would a similar file exist on the PC version?

**Comment by AntonnMal** [comment]
I believe the addresses haven't changed, so you can use the vita FPK file.

**Comment by crispbitload** [comment]
Alright! I'll grab the links again and test once maintenance is over and report back.

Also, would using another proxy (ex. Router Proxy) cause a conflict?

**Comment by AntonnMal** [comment]
I think no, but I'm not sure.

**Comment by crispbitload** [comment]
So I attempted to log in, and with the injected RSA key I keep receiving a "Server timed out" error. Even with link replacement, I receive this error. Launching the game without the injector does not cause the message to occur. (Also tested with and without the Ryuker proxy enabled via VPN)

**Comment by AntonnMal** [comment]
In the proxy window do you see 'Got connection'?

**Comment by crispbitload** [comment]
I do not see the got connection message

![Screenshot 2024-07-10 180759](https://github.com/AntonnMal/pso2-proxy/assets/84352107/6636a5b8-5dac-4996-957f-8a5cad0797db)

**Comment by AntonnMal** [comment]
Then I'm assuming that you didn't configure the injector correctly. Address definitions should be in the following format:
```
[[addresses]]
old = "<server ip>"
new = "<proxy ip>
```

**Comment by crispbitload** [comment]
That is most likely the reason...

Where would I get the proxy IP's? Would it be something local (like my home IP)? I never configured a proxy before, so excuse my inexperience.

**Comment by AntonnMal** [comment]
It's the IP of the PC that you have the proxy open (in your case `localhost` should work)

**Comment by crispbitload** [comment]
Still no luck, I even tried the IP addresses, which weirdly the config just reset itself after I did so.

Using the server links/IPs from http://the-ghf-clan.de/pso2serverstatus.html

![Screenshot 2024-07-10 192850](https://github.com/AntonnMal/pso2-proxy/assets/84352107/d11eb8cc-a793-4160-976f-3612b9969219)

![Screenshot 2024-07-10 192920](https://github.com/AntonnMal/pso2-proxy/assets/84352107/7a3433cd-8f8c-46b9-ae4c-4fc75c94bf62)

![Screenshot 2024-07-10 192934](https://github.com/AntonnMal/pso2-proxy/assets/84352107/1cb0eba7-e87b-45d4-a153-0ed472f58490)

**Comment by AntonnMal** [comment]
The proxy should first say `Got connection` when you load the ship selection screen. Since you say that you don't see that I'm assuming that the client connects to some different ship info server. Also, do the ship statuses show up? If so, then you'll probably need to use Wireshark to get the IPs (and hostnames from DNS packets). If they don't, then I going to ask you also use Wireshark to get the address that the client is trying to connect. 

Sorry, I just don't use JP version.

**Comment by crispbitload** [comment]
On JP it shows the ships online, but it errors out with "Server timed out" after the SEGA ID screen.

It's fine, honestly I might use my alt account and grab packets on the Global version instead. Can I grab both English and Japanese item ID's using global? Along with that, would grabbing packets related to functions like using AC and gacha help? 

lastly, would it be more preferred to grab packets on classic instead of NGS?

**Comment by AntonnMal** [comment]
I believe that you can use global to grab both languages, it depends on the selected language in game. AC and trading packets would be very nice to have. Also, NGS sends different packets in a lot of cases, so classic packets are preferred.

**Comment by crispbitload** [comment]
Alright! Also does it matter what version of the game I am using? The microsoft store version to be more specific (I also have the steam version, but don't have an alt account on steam)

**Comment by AntonnMal** [comment]
The version you use doesn't matter.

It's fine to to multiple action on the same capture as long as there is some identification as to what you were doing (a chat message would suffice)

**Comment by crispbitload** [comment]
I got the proxy running, however every time I run PSO2 with the proxy enabled, all the servers are stuck on maintenance.

![Screenshot 2024-07-11 210114](https://github.com/user-attachments/assets/b59688f4-db25-40a2-b2ad-e699bfe963b3)

This happens when I use my direct IP address of my PC (Via ethernet). Using localhost makes the proxy not run and error out under error 240.

Configurations included

![Screenshot 2024-07-11 211230](https://github.com/user-attachments/assets/9781fa07-c99a-4575-bbbd-8b1a41cfb908)

**Comment by AntonnMal** [comment]
From the proxy window it seems that it can't connect to sega servers for some reason. The server is correct and I've checked that it is up.

**Comment by crispbitload** [comment]
If it helps, here is the file structures of both the proxy and injector (output) as well.

![Screenshot 2024-07-11 213800](https://github.com/user-attachments/assets/fe334756-4fe1-411c-b2ab-beeeeb8f80a3)

**Comment by AntonnMal** [comment]
Can you check if you can connect to the server (using ncat for example) under different conditions (i.e. when running the game w/o injector or with it, running the proxy in the background)?

**Comment by crispbitload** [comment]
Alright, what command would I use on ncat to listen/record me testing connecting to the servers?

**Comment by AntonnMal** [comment]
`.\ncat.exe gs0100.westus2.cloudapp.azure.com 12180`

**Comment by crispbitload** [comment]
Ok I feel stupid...

After changing the link back to gs0100.westus2.cloudapp.azure.com 12180 on the proxy, I no longer receive errors.

![Screenshot 2024-07-12 002245](https://github.com/user-attachments/assets/fe8005af-9db6-4898-90c0-feb008888620)

**Comment by tired-developer55** [comment]
Sorry to bump this, for the life of me I couldn't get this to hook. Did something change? I noticed I don't have the injector.exe fromo the above screenshot even after cargo build.
I downloaded the release and extracted it into the sub folder and changed the config.toml, then I ran the proxy to generate my own key and picked up Segakey1 from sub folder since it was already there. I'm not sure what I missed.
I'm running JP client but it had a game update just some hours ago, could that be related?

**Comment by AntonnMal** [comment]
> Sorry to bump this.

Don't bump old issues on github, because it sends a notification to the participants. Open a new issue and mention the other issue by link or by id.

> changed the config.toml

Changed what exactly? JP servers have different IPs. You mention that you have the keys in the sub folder, that means that the injector ran, so it's probably a config issue.

> I noticed I don't have the injector.exe fromo the above screenshot even after cargo build.

`injector.exe` was only for GameGuard. Only two relevant DLLs are `rsa_inject.dll` from the main source tree and `dllhijack.dll`/`eos_gaming.dll` from [pso2-rsa-injector/dllhijack](https://github.com/AntonnMal/pso2-rsa-injector/tree/master/dllhijack)

Please open a new issue on the injector repo.
